layout(location = 0) uniform float blend_value;
layout(location = 1) uniform float sphere_radius;

float scene(in vec3 point)
{
	float obj = sd_box(point, vec3(1.0, 1.0, 1.0));
	obj = op_union(obj, sd_sphere(point - vec3(1.5, 1.5, 0.0), sphere_radius));
	return op_blend(obj, sd_plane(point, vec4(0.0, 1.0, 0.0, 0.5)), blend_value);
}

#define ENABLE_SHADOW
#define SOFT_SHADOW
#define ENABLE_AMBIENT_OCCLUSION
