layout(location = 0) uniform float blend_value; // min: 0.0; max: 0.3; default: 0.08;
layout(location = 1) uniform float sphere_radius; // min: 0.5; max: 3.0; default: 1.3;

float scene(in vec3 point)
{
	float obj = sd_box(point, vec3(1.0, 1.0, 1.0));
	obj = op_union(obj, sd_sphere(point - vec3(1.5, 1.5, 0.0), sphere_radius));
	return op_blend(obj, sd_plane(point, vec4(0.0, 1.0, 0.0, 0.5)), blend_value);
}

#define SOFT_SHADOW
#define AMBIENT_OCCLUSION
